### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Slepwin** [ipchama/dupligator#9]
Could you please build docker image.

**Comment by ipchama** [comment]
Not sure why I didn't get the notification message for this.  Sure, I can get a Dockerfile and example docker-compose.yml and put something on Dockerhub, probably in a few days.

**Comment by ipchama** [comment]
Took me a bit to get back to my computer, but Dockerfile, docker-compose.yml, and pre-made image at docker hub are all up:

https://github.com/ipchama/dupligator/blob/master/Dockerfile
https://github.com/ipchama/dupligator/blob/master/docker-compose.yml

https://hub.docker.com/repository/docker/dockerhama/dupligator
